apiVersion: skaffold/v2beta4
kind: Config
metadata:
  name: governor
build:
  artifacts:
    - image: docker.pkg.dev.localhost:8080/governor
      context: '.'
  local:
    push: false
    useDockerCLI: true
    useBuildkit: true
    concurrency: 1
  insecureRegistries:
    - docker.pkg.dev.localhost:8080
deploy:
  kustomize:
    paths:
      - skaffolddev
