apiVersion: 'kustomize.config.k8s.io/v1beta1'
kind: 'Kustomization'
namespace: 'governor'
bases:
  - './postgres'
  - './redis'
  - './minio'
  - './nats'
  - './natsstream'
resources:
  - './app/rsrc/namespace.yaml'
