version: "3.7"

services:
  governor:
    image: governor:latest
    volumes:
      - ./config:/config
      - ./public:/public
      - ./templates:/templates
    depends_on:
      - "postgres"
      - "redis"
      - "minio"
      - "messenger"
      - "mail"
    ports:
      - 8080:8080
    restart: unless-stopped
