version: "3.3"

services:
  postgres:
    ports:
      - 5432:5432

  redis:
    ports:
      - 6379:6379

  minio:
    ports:
      - 9000:9000

  mail:
    ports:
      - 1025:1025
      - 8025:8025
