roles:
  - kind: kube
    kubemount: kubernetes
    role: governor-register-governor
    service_account: register-governor
    namespace: governor
    policies:
      - governor-governor-register
    ttl: 1m
    maxttl: 5m
  - kind: kube
    kubemount: kubernetes
    role: governor-governor
    service_account: governor
    namespace: governor
    policies:
      - governor-governor-service
      - governor-postgres-rw-consumer
      - governor-postgres-ro-consumer
      - governor-redis-consumer
      - governor-minio-consumer
      - governor-nats-consumer
    ttl: 1h
    maxttl: 24h
