roles:
  - kind: kube
    kubemount: kubernetes
    role: governor-register-minio
    service_account: register-minio
    namespace: governor
    policies:
      - governor-minio-register
    ttl: 1m
    maxttl: 5m
  - kind: kube
    kubemount: kubernetes
    role: governor-minio
    service_account: minio
    namespace: governor
    policies:
      - governor-minio-service
    ttl: 1m
    maxttl: 5m
