roles:
  - kind: kube
    kubemount: kubernetes
    role: governor-register-postgres
    service_account: register-postgres
    namespace: governor
    policies:
      - governor-postgres-register
    ttl: 1m
    maxttl: 5m
  - kind: kube
    kubemount: kubernetes
    role: governor-postgres
    service_account: postgres
    namespace: governor
    policies:
      - governor-postgres-service
    ttl: 1m
    maxttl: 5m
