roles:
  - kind: kube
    kubemount: kubernetes
    role: governor-register-nats
    service_account: register-nats
    namespace: governor
    policies:
      - governor-nats-register
    ttl: 1m
    maxttl: 5m
  - kind: kube
    kubemount: kubernetes
    role: governor-nats
    service_account: nats
    namespace: governor
    policies:
      - governor-nats-service
    ttl: 1m
    maxttl: 5m
