roles:
  - kind: kube
    kubemount: kubernetes
    role: governor-register-redis
    service_account: register-redis
    namespace: governor
    policies:
      - governor-redis-register
    ttl: 1m
    maxttl: 5m
  - kind: kube
    kubemount: kubernetes
    role: governor-redis
    service_account: redis
    namespace: governor
    policies:
      - governor-redis-service
    ttl: 1m
    maxttl: 5m
