apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: governor
configMapGenerator:
  - name: nats-register-scripts
    files:
      - register.sh
      - _init_lib.sh
  - name: register-nats-opts
    literals:
      - passlen=64
      - curlbackoff=5
      - curlreauth=3
      - vaultaddr=http://vault.vault.svc.cluster.local:8200
      - vaultrole=governor-register-nats
      - vaultkubemount=kubernetes
      - kvmount=kv
      - kvpath=infra/governor/nats
resources:
  - job.yaml
