mode: 'INFO'
port: '8080'
baseurl: '/api'
maxreqsize: '2M'
vault:
  addr: 'vault.vault.svc.cluster.local'
  k8s:
    auth: true
    role: 'governor-role'
database:
  auth: 'database/creds/governor-role'
  dbname: 'postgres'
  host: 'postgres-postgres.governor.svc.cluster.local'
  port: '5432'
  sslmode: 'disable'
  hbinterval: 5
  hbmaxfail: 5
kvstore:
  auth: 'kv/data/infra/governor/redis'
  dbname: 0
  host: 'redis-redis.governor.svc.cluster.local'
  port: '6379'
  hbinterval: 5
  hbmaxfail: 5
objstore:
  auth: 'kv/data/infra/governor/minio'
  host: 'minio'
  port: '9000'
  sslmode: false
  location: 'us-east-1'
  hbinterval: 5
  hbmaxfail: 5
msgqueue:
  auth: 'kv/data/infra/governor/natsstream'
  host: 'natsstream-nats-streaming.svc.cluster.local'
  port: '4222'
  cluster: 'nss'
  hbinterval: 5
  hbmaxfail: 5
pubsub:
  auth: 'kv/data/infra/governor/nats'
  host: 'nats-nats.svc.cluster.local'
  port: '4222'
  hbinterval: 5
  hbmaxfail: 5
template:
  dir: templates
mail:
  host: mail
  port: 1025
  # port: 587
  fromaddress: no-reply@xorkevin.com
  fromname: Governor
  workersize: 2
  connmsgcap: 100
role:
  rolecache: 24h
token:
  issuer: governor
  # secret: secret
user:
  accesstime: 5m
  refreshtime: 4380h
  refreshcache: 24h
  confirmtime: 24h
  passwordresettime: 24h
  newloginemail: true
  passwordminsize: 8
  userapproval: false
courier:
  cachetime: 24h
