mode: DEBUG
logoutput: STDOUT
port: 8080
baseurl: /api
templatedir: templates
maxreqsize: 2M
maxheadersize: 1M
maxconnread: 5s
maxconnheader: 2s
maxconnwrite: 5s
maxconnidle: 5s
alloworigins: []
routerewrite:
  - host: go.governor.dev.home:8080
    methods: ['GET']
    pattern: '^/([A-Za-z0-9_-]{2,}(?:/image)?)$'
    replace: /api/courier/link/$1
  - host: governor.dev.home:8080
    methods: ['GET']
    pattern: '^\/\.well-known\/openid-configuration$'
    replace: /api/oauth/openid-configuration
vault:
  addr: http://vault.vault.svc.cluster.local:8200
  k8s:
    auth: true
    role: governor-governor-role
database:
  auth: database/creds/governor-postgres-role
  dbname: postgres
  host: postgres-postgres.governor.svc.cluster.local
  port: 5432
  sslmode: disable
  hbinterval: 5
  hbmaxfail: 5
kvstore:
  auth: kv/data/infra/governor/redis
  dbname: 0
  host: redis-redis.governor.svc.cluster.local
  port: 6379
  hbinterval: 5
  hbmaxfail: 5
objstore:
  auth: kv/data/infra/governor/minio
  host: minio-minio.governor.svc.cluster.local
  port: 9000
  sslmode: false
  location: us-east-1
  hbinterval: 5
  hbmaxfail: 5
msgqueue:
  auth: kv/data/infra/governor/natsstream
  host: natsstream-nats-streaming.governor.svc.cluster.local
  port: 4222
  cluster: nats-streaming
  hbinterval: 5
  hbmaxfail: 5
pubsub:
  auth: kv/data/infra/governor/nats
  host: nats-nats.governor.svc.cluster.local
  port: 4222
  hbinterval: 5
  hbmaxfail: 5
template:
  dir: templates
mail:
  auth: kv/data/external/smtp
  host: localhost
  port: 587
  fromaddress: no-reply@xorkevin.com
  fromname: Governor
role:
  rolecache: 24h
apikey:
  scopecache: 24h
token:
  tokensecret: kv/data/app/governor/token
  rsakey: kv/data/app/governor/rsakey
  issuer: http://governor.dev.home:8080
  audience: governor
oauth:
  keycache: 24h
  issuer: http://governor.dev.home:8080
  epbase: http://governor.dev.home:8080/api/oauth
  epauthorization: /auth/authorize
  eptoken: /auth/token
  epuserinfo: /userinfo
  epjwks: /jwks
user:
  accesstime: 5m
  refreshtime: 4380h
  refreshcache: 24h
  confirmtime: 24h
  passwordresettime: 24h
  newloginemail: true
  passwordminsize: 8
  userapproval: false
  email:
    url:
      base: http://governor.dev.home:8080
courier:
  fallbacklink: http://governor.dev.home:8080
  linkprefix: http://go.governor.dev.home:8080
  cachetime: 24h
