mode: 'INFO'
port: '8080'
baseurl: '/api'
maxreqsize: '2M'
vault:
  addr: 'vault.vault.svc.cluster.local'
  k8s:
    auth: true
    role: 'governor-role'
database:
  auth: 'database/creds/governor-role'
  dbname: 'postgres'
  host: 'postgres-postgres.governor.svc.cluster.local'
  port: '5432'
  sslmode: 'disable'
kvstore:
  password: admin
  dbname: 0
  host: redis
  port: 6379
objstore:
  keyid: admin
  keysecret: adminsecret
  host: minio
  port: 9000
  sslmode: false
msgqueue:
  host: messenger
  port: 4222
  cluster: nss
  token: admin
msgstoredb:
  user: nss
  password: admin
  dbname: nss_db
  host: messagestore
  port: 5432
  sslmode: disable
pubsub:
  host: pubsub
  port: 4222
  token: admin
template:
  dir: templates
mail:
  host: mail
  port: 1025
  # port: 587
  fromaddress: no-reply@xorkevin.com
  fromname: Governor
  workersize: 2
  connmsgcap: 100
role:
  rolecache: 24h
token:
  issuer: governor
  # secret: secret
user:
  accesstime: 5m
  refreshtime: 4380h
  refreshcache: 24h
  confirmtime: 24h
  passwordresettime: 24h
  newloginemail: true
  passwordminsize: 8
  userapproval: false
courier:
  cachetime: 24h
