apiVersion: v1
kind: ServiceAccount
metadata:
  name: register-postgres

---
apiVersion: batch/v1
kind: Job
metadata:
  name: register-postgres
spec:
  backoffLimit: 4
  template:
    metadata:
      labels:
        app: register-postgres
        app.kubernetes.io/name: register-postgres
        app.kubernetes.io/instance: register-postgres
        app.kubernetes.io/version: 13-alpine
        app.kubernetes.io/component: database
        app.kubernetes.io/part-of: governor
        app.kubernetes.io/managed-by: anvil
    spec:
      serviceAccountName: register-postgres
      restartPolicy: OnFailure
      containers:
        - name: register
          image: xorkevin/alpine-utils:3
          command: ['sh']
          args: ['/home/postgres/register.sh']
          env:
            - name: PASS_LEN
              valueFrom:
                configMapKeyRef:
                  name: register-postgres-opts
                  key: passlen
                  optional: true
            - name: CURL_BACKOFF
              valueFrom:
                configMapKeyRef:
                  name: register-postgres-opts
                  key: curlbackoff
                  optional: true
            - name: CURL_REAUTH
              valueFrom:
                configMapKeyRef:
                  name: register-postgres-opts
                  key: curlreauth
                  optional: true
            - name: VAULT_ADDR
              valueFrom:
                configMapKeyRef:
                  name: register-postgres-opts
                  key: vaultaddr
            - name: VAULT_ROLE
              valueFrom:
                configMapKeyRef:
                  name: register-postgres-opts
                  key: vaultrole
            - name: VAULT_KUBE_MOUNT
              valueFrom:
                configMapKeyRef:
                  name: register-postgres-opts
                  key: vaultkubemount
            - name: DB_MOUNT
              valueFrom:
                configMapKeyRef:
                  name: register-postgres-opts
                  key: dbmount
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: register-postgres-opts
                  key: dbname
            - name: DB_CONN
              valueFrom:
                configMapKeyRef:
                  name: register-postgres-opts
                  key: dbconn
            - name: DB_TTL
              valueFrom:
                configMapKeyRef:
                  name: register-postgres-opts
                  key: dbttl
            - name: DB_MAX_TTL
              valueFrom:
                configMapKeyRef:
                  name: register-postgres-opts
                  key: dbmaxttl
            - name: KV_MOUNT
              valueFrom:
                configMapKeyRef:
                  name: register-postgres-opts
                  key: kvmount
            - name: KV_PATH
              valueFrom:
                configMapKeyRef:
                  name: register-postgres-opts
                  key: kvpath
          volumeMounts:
            - name: register-scripts
              mountPath: /home/postgres
      volumes:
        - name: register-scripts
          configMap:
            name: postgres-register-scripts
