apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: governor
configMapGenerator:
  - name: postgres-register-scripts
    files:
      - register.sh
      - _init_lib.sh
      - rolecreate.sql
      - rolerocreate.sql
      - rolerevoke.sql
  - name: register-postgres-opts
    literals:
      - passlen=64
      - curlbackoff=5
      - curlreauth=3
      - vaultaddr=http://vault.vault.svc.cluster.local:8200
      - vaultrole=governor-register-postgres
      - vaultkubemount=kubernetes
      - dbmount=database
      - dbname=governor-postgres
      - dbconn="postgresql://{{username}}:{{password}}@postgres.governor.svc.cluster.local:5432/postgres?sslmode=disable"
      - dbttl=1h
      - dbmaxttl=24h
      - kvmount=kv
      - kvpath=infra/governor/postgres
resources:
  - job.yaml
