{{ $svc := .Vars.kube.service.name -}}
{{ $rgsvc := printf "register-%s" .Vars.kube.service.name -}}
{{ $rgsvcopts := printf "%s-opts" $rgsvc -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $rgsvc }}

---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $rgsvc }}
spec:
  backoffLimit: 4
  template:
    metadata:
      labels:
        app: {{ $rgsvc }}
        app.kubernetes.io/name: register-postgres
        app.kubernetes.io/instance: {{ $rgsvc }}
        app.kubernetes.io/version: {{ .Vars.kube.service.image.version }}
        app.kubernetes.io/component: {{ .Vars.kube.label.component }}
        app.kubernetes.io/part-of: {{ .Vars.kube.label.partof }}
        app.kubernetes.io/managed-by: anvil
    spec:
      serviceAccountName: {{ $rgsvc }}
      restartPolicy: OnFailure
      containers:
        - name: register
          image: {{ .Vars.kube.register.image.name }}:{{ .Vars.kube.register.image.version }}
          command: ['sh']
          args: ['/home/postgres/register.sh']
          env:
            - name: PASS_LEN
              valueFrom:
                configMapKeyRef:
                  name: {{ $rgsvcopts }}
                  key: passlen
                  optional: true
            - name: CURL_BACKOFF
              valueFrom:
                configMapKeyRef:
                  name: {{ $rgsvcopts }}
                  key: curlbackoff
                  optional: true
            - name: CURL_REAUTH
              valueFrom:
                configMapKeyRef:
                  name: {{ $rgsvcopts }}
                  key: curlreauth
                  optional: true
            - name: VAULT_ADDR
              valueFrom:
                configMapKeyRef:
                  name: {{ $rgsvcopts }}
                  key: vaultaddr
            - name: VAULT_ROLE
              valueFrom:
                configMapKeyRef:
                  name: {{ $rgsvcopts }}
                  key: vaultrole
            - name: VAULT_KUBE_MOUNT
              valueFrom:
                configMapKeyRef:
                  name: {{ $rgsvcopts }}
                  key: vaultkubemount
            - name: DB_MOUNT
              valueFrom:
                configMapKeyRef:
                  name: {{ $rgsvcopts }}
                  key: dbmount
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ $rgsvcopts }}
                  key: dbname
            - name: DB_CONN
              valueFrom:
                configMapKeyRef:
                  name: {{ $rgsvcopts }}
                  key: dbconn
            - name: DB_TTL
              valueFrom:
                configMapKeyRef:
                  name: {{ $rgsvcopts }}
                  key: dbttl
            - name: DB_MAX_TTL
              valueFrom:
                configMapKeyRef:
                  name: {{ $rgsvcopts }}
                  key: dbmaxttl
            - name: KV_MOUNT
              valueFrom:
                configMapKeyRef:
                  name: {{ $rgsvcopts }}
                  key: kvmount
            - name: KV_PATH
              valueFrom:
                configMapKeyRef:
                  name: {{ $rgsvcopts }}
                  key: kvpath
          volumeMounts:
            - name: register-scripts
              mountPath: /home/postgres
      volumes:
        - name: register-scripts
          configMap:
            name: {{ $svc }}-register-scripts
