apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: {{ .Vars.kube.namespace }}
configMapGenerator:
  - name: init-scripts
    files:
      - init.sh
      - _init_lib.sh
  - name: {{ .Vars.kube.service.name }}-opts
    literals:
      - curlbackoff={{ .Vars.vault.curlbackoff }}
      - curlreauth={{ .Vars.vault.curlreauth }}
      - vaultaddr={{ .Vars.vault.addr }}
      - vaultrole={{ .Vars.kube.namespace }}-{{ .Vars.kube.service.name }}
      - vaultkubemount={{ .Vars.vault.kubemount }}
      - kvmount={{ .Vars.vault.kvmount }}
      - kvpath={{ with .Vars.vault.kvprefix }}{{ . }}/{{ end }}{{ .Vars.kube.namespace }}/{{ .Vars.kube.service.name }}
{{- with .Vars.initscripts }}
  - name: initscripts
    files:
      {{- range . }}
      - {{ . }}
      {{- end }}
{{- end }}
resources:
  - service.yaml
