apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Vars.kube.service.name }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Vars.kube.service.name }}-internal
spec:
  selector:
    app: {{ .Vars.kube.service.name }}
  ports:
    - name: postgres
      port: 5432
  clusterIP: None

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Vars.kube.service.name }}
spec:
  selector:
    app: {{ .Vars.kube.service.name }}
  ports:
    - name: postgres
      port: 5432

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Vars.kube.service.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Vars.kube.service.name }}
  serviceName: {{ .Vars.kube.service.name }}-internal
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Vars.kube.service.name }}
        app.kubernetes.io/name: postgres
        app.kubernetes.io/instance: {{ .Vars.kube.service.name }}
        app.kubernetes.io/version: {{ .Vars.kube.service.image.version }}
        app.kubernetes.io/component: {{ .Vars.kube.label.component }}
        app.kubernetes.io/part-of: {{ .Vars.kube.label.partof }}
        app.kubernetes.io/managed-by: anvil
    spec:
      serviceAccountName: {{ .Vars.kube.service.name }}
      initContainers:
        - name: getpass
          image: {{ .Vars.kube.service.init.image.name }}:{{ .Vars.kube.service.init.image.version }}
          command: ['sh']
          args: ['/home/postgres/init.sh']
          env:
            - name: CURL_BACKOFF
              valueFrom:
                configMapKeyRef:
                  name: {{ .Vars.kube.service.name }}-opts
                  key: curlbackoff
                  optional: true
            - name: CURL_REAUTH
              valueFrom:
                configMapKeyRef:
                  name: {{ .Vars.kube.service.name }}-opts
                  key: curlreauth
                  optional: true
            - name: VAULT_ADDR
              valueFrom:
                configMapKeyRef:
                  name: {{ .Vars.kube.service.name }}-opts
                  key: vaultaddr
            - name: VAULT_ROLE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Vars.kube.service.name }}-opts
                  key: vaultrole
            - name: VAULT_KUBE_MOUNT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Vars.kube.service.name }}-opts
                  key: vaultkubemount
            - name: KV_MOUNT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Vars.kube.service.name }}-opts
                  key: kvmount
            - name: KV_PATH
              valueFrom:
                configMapKeyRef:
                  name: {{ .Vars.kube.service.name }}-opts
                  key: kvpath
          volumeMounts:
            - name: config-pass
              mountPath: /etc/postgrespass
            - name: init-scripts
              mountPath: /home/postgres
      containers:
        - name: postgres
          image: {{ .Vars.kube.service.image.name }}:{{ .Vars.kube.service.image.version }}
          env:
            - name: POSTGRES_PASSWORD_FILE
              value: /etc/postgrespass/pass.txt
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_DB
              value: postgres
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_INITDB_ARGS
              value: '--auth-local=trust --auth-host=scram-sha-256'
            - name: POSTGRES_HOST_AUTH_METHOD
              value: scram-sha-256
          ports:
            - name: postgres
              containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: config-pass
              mountPath: /etc/postgrespass
            - name: initscripts
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: config-pass
          emptyDir: {}
        - name: init-scripts
          configMap:
            name: init-scripts
        - name: initscripts
          configMap:
            name: initscripts
            optional: true
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Vars.kube.service.storage.amount }}
