version: v0.1.0
mode: DEBUG
port: 8080
baseurl: /api
postgres:
  user: postgres
  password: admin
  dbname: governor
  host: localhost
  port: 5432
  sslmode: disable
redis:
  password: admin
  dbname: 0
  host: localhost
  port: 6379
userauth:
  issuer: governor_auth
  secret: secret
  duration: 15m
  refresh_duration: 168h
mail:
  username: admin
  password: admin
  host: localhost
  port: 587
