appname: governor
version: v0.1.0
mode: DEBUG
port: 8080
baseurl: /api
publicdir: public
postgres:
  user: postgres
  password: admin
  dbname: governor
  host: localhost
  port: 5432
  sslmode: disable
redis:
  password: admin
  dbname: 0
  host: localhost
  port: 6379
userauth:
  issuer: governor_auth
  secret: secret
  duration: 15m
  refresh_duration: 168h
user:
  confirm_duration: 24h
  password_reset_duration: 24h
mail:
  username: test
  password: test
  host: localhost
  port: 1025
  from_address: gov@hack.com
  insecure: true
post:
  archive_time: 2688h
