version: v0.1.0
mode: DEBUG
port: 8080
baseurl: /api/v1
postgres:
  user: postgres
  password: admin
  dbname: governor
  host: localhost
  port: 5432
  sslmode: disable
userauth:
  issuer: governor_auth
  secret: secret
  duration: 5m
