appname: governor
version: v0.1.0
mode: INFO
port: 8080
baseurl: /api
publicdir: public
postgres:
  user: postgres
  password: admin
  dbname: governor
  host: gpostgres
  port: 5432
  sslmode: disable
redis:
  password: admin
  dbname: 0
  host: gredis
  port: 6379
minio:
  key_id: admin
  key_secret: adminsecret
  host: gminio
  port: 9000
  sslmode: false
userauth:
  issuer: governor_auth
  secret: secret
  duration: 15m
  refresh_duration: 168h
user:
  confirm_duration: 24h
  password_reset_duration: 24h
mail:
  username: test
  password: test
  host: gmail
  port: 1025
  # port: 587
  from_address: gov@hack.com
post:
  archive_time: 2688h
