mode: INFO
port: 8080
baseurl: /api
publicdir: public
maxreqsize: 2M
alloworigins:
  - http://localhost
database:
  user: postgres
  password: admin
  dbname: governor
  host: postgres
  port: 5432
  sslmode: disable
kvstore:
  password: admin
  dbname: 0
  host: redis
  port: 6379
objstore:
  keyid: admin
  keysecret: adminsecret
  host: minio
  port: 9000
  sslmode: false
msgqueue:
  host: messenger
  port: 4222
  cluster: nss
template:
  dir: templates
userauth:
  issuer: governor
  secret: secret
  duration: 15m
  refresh_duration: 4380h
  refresh_cache_duration: 24h
user:
  confirm_duration: 1h
  password_reset_duration: 1h
  new_login_email: true
  password_min_size: 8
courier:
  cache_time: 1m
mail:
  host: mail
  port: 1025
  # port: 587
  from_address: gov@xorkevin.com
  from_name: Hackform
  buffer_size: 1024
  worker_size: 2
  conn_msg_cap: 100
post:
  archive_time: 2688h
