appname: governor
version: v0.1.0
mode: INFO
port: 8080
baseurl: /api
publicdir: public
templatedir: templates
max_req_size: 2M
allow_origins:
  - http://localhost
postgres:
  user: postgres
  password: admin
  dbname: governor
  host: postgres
  port: 5432
  sslmode: disable
redis:
  password: admin
  dbname: 0
  host: redis
  port: 6379
minio:
  key_id: admin
  key_secret: adminsecret
  host: minio
  port: 9000
  sslmode: false
userauth:
  issuer: governor
  secret: secret
  duration: 15m
  refresh_duration: 168h
user:
  confirm_duration: 24h
  password_reset_duration: 24h
mail:
  username: test
  password: test
  host: mail
  port: 1025
  # port: 587
  from_address: gov@hack.com
  buffer_size: 1024
  worker_size: 2
post:
  archive_time: 2688h
