mode: DEBUG
port: 8080
baseurl: /api
publicdir: public
templatedir: templates
maxreqsize: 2M
alloworigins:
  - http://localhost:3000
  - http://localhost:3001
  - http://localhost:3030
  - http://localhost:3031
routerewrite:
  '/link/*': '/api/courier/link/$1'
database:
  user: postgres
  password: admin
  dbname: governor
  host: localhost
  port: 5432
  sslmode: disable
kvstore:
  password: admin
  dbname: 0
  host: localhost
  port: 6379
objstore:
  keyid: admin
  keysecret: adminsecret
  host: localhost
  port: 9000
  sslmode: false
nats:
  host: localhost
  port: 4222
  cluster: nss
userauth:
  issuer: governor
  secret: secret
  duration: 15m
  refresh_duration: 4380h
  refresh_cache_duration: 24h
user:
  confirm_duration: 1h
  password_reset_duration: 1h
  new_login_email: true
  password_min_size: 8
courier:
  fallback_link: http://localhost:8080
  link_prefix: http://localhost:8080/link
  cache_time: 1m
mail:
  host: localhost
  port: 1025
  from_address: gov@xorkevin.com
  from_name: Hackform
  insecure: true
  buffer_size: 1024
  worker_size: 2
  conn_msg_cap: 100
post:
  archive_time: 2688h
