mode: INFO
port: 8080
baseurl: /api
publicdir: public
maxreqsize: 2M
alloworigins:
  - http://localhost
database:
  user: postgres
  password: admin
  dbname: governor
  host: postgres
  port: 5432
  sslmode: disable
kvstore:
  password: admin
  dbname: 0
  host: redis
  port: 6379
objstore:
  keyid: admin
  keysecret: adminsecret
  host: minio
  port: 9000
  sslmode: false
msgqueue:
  host: messenger
  port: 4222
  cluster: nss
template:
  dir: templates
mail:
  host: mail
  port: 1025
  # port: 587
  fromaddress: gov@xorkevin.com
  fromname: Governor
  workersize: 2
  connmsgcap: 100
gate:
  issuer: governor
  # secret: secret
user:
  accesstime: 5m
  refreshtime: 4380h
  refreshcache: 24h
  confirmtime: 24h
  passwordresettime: 24h
  newloginemail: true
  passwordminsize: 8
  issuer: governor
  # secret: secret
courier:
  cache_time: 1m
