apiVersion: apps/v1
kind: Deployment
metadata:
  name: governor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: governor
  template:
    metadata:
      labels:
        app: governor
    spec:
      serviceAccountName: governor
      initContainers:
        - name: gentokensecret
          image: xorkevin/alpine-utils:3
          command: ['sh']
          args: ['/home/governor/init.sh']
          env:
            - name: PASS_LEN
              valueFrom:
                configMapKeyRef:
                  name: init-opts
                  key: passlen
                  optional: true
            - name: RSA_BITS
              valueFrom:
                configMapKeyRef:
                  name: init-opts
                  key: rsabits
                  optional: true
            - name: CURL_BACKOFF
              valueFrom:
                configMapKeyRef:
                  name: init-opts
                  key: curlbackoff
                  optional: true
            - name: CURL_REAUTH
              valueFrom:
                configMapKeyRef:
                  name: init-opts
                  key: curlreauth
                  optional: true
            - name: VAULT_ADDR
              valueFrom:
                configMapKeyRef:
                  name: init-opts
                  key: vaultaddr
            - name: VAULT_ROLE
              valueFrom:
                configMapKeyRef:
                  name: init-opts
                  key: vaultrole
            - name: KV_PATH
              valueFrom:
                configMapKeyRef:
                  name: init-opts
                  key: kvpath
            - name: KV_PATH_RSA
              valueFrom:
                configMapKeyRef:
                  name: init-opts
                  key: kvpathrsa
          volumeMounts:
            - name: init-scripts
              mountPath: /home/governor
      containers:
        - name: governor
          image: docker.pkg.dev.localhost:8080/governor
          env:
            - name: HOME
              value: /home/governor
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /api/healthz/ready
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /api/healthz/live
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 15
          volumeMounts:
            - name: config
              mountPath: /home/governor/config
            - name: templates
              mountPath: /home/governor/templates
      volumes:
        - name: init-scripts
          configMap:
            name: init-scripts
        - name: config
          configMap:
            name: config
        - name: templates
          configMap:
            name: templates
