{{ $svc := .Vars.kube.service.name -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $svc }}
spec:
{{- with .Vars.kube.service.ingressRoute.entryPoints }}
  entryPoints:
    {{- range . }}
    - {{ . }}
    {{- end }}
{{- end }}
{{- with .Vars.kube.service.ingressRoute.matchRule }}
  routes:
    - kind: Rule
      match: {{ . }}
      services:
        - kind: Service
          scheme: http
          name: governor
          port: 8080
{{- end }}
