apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailhog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailhog
  template:
    metadata:
      labels:
        app: mailhog
    spec:
      containers:
        - name: mailhog
          image: mailhog/mailhog
          ports:
            - name: smtp
              containerPort: 1025
            - name: http
              containerPort: 8025

---
apiVersion: v1
kind: Service
metadata:
  name: mailhog
spec:
  ports:
    - name: smtp
      port: 1025
    - name: http
      port: 8025
  selector:
    app: mailhog

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: mailhog
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`mailhog.dev.localhost`)
      services:
        - kind: Service
          scheme: http
          name: mailhog
          port: 8025
