apiVersion: apps/v1
kind: Deployment
metadata:
  name: governor
spec:
  template:
    spec:
      containers:
        - name: governor
          env:
            - name: GOV_MAIL_HOST
              value: mailhog.governor.svc.cluster.local
            - name: GOV_MAIL_PORT
              value: '1025'
            - name: GOV_MAIL_INSECURE
              value: 'true'
            - name: GOV_ALLOWORIGINS
              value: http://governor.dev.home:3000
