apiVersion: v1
kind: ServiceAccount
metadata:
  name: nats

---
apiVersion: v1
kind: Service
metadata:
  name: nats-internal
spec:
  selector:
    app: nats
  ports:
    - name: nats
      port: 4222
    - name: cluster
      port: 6222
  clusterIP: None

---
apiVersion: v1
kind: Service
metadata:
  name: nats
spec:
  selector:
    app: nats
  ports:
    - name: nats
      port: 4222

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nats
spec:
  selector:
    matchLabels:
      app: nats
  serviceName: nats-internal
  replicas: 1
  template:
    metadata:
      labels:
        app: nats
        app.kubernetes.io/name: nats
        app.kubernetes.io/instance: nats
        app.kubernetes.io/version: 2-alpine
        app.kubernetes.io/component: pubsub
        app.kubernetes.io/part-of: governor
        app.kubernetes.io/managed-by: anvil
    spec:
      serviceAccountName: nats
      initContainers:
        - name: getpass
          image: xorkevin/alpine-utils:3
          command: ['sh']
          args: ['/home/nats/init.sh']
          env:
            - name: CURL_BACKOFF
              valueFrom:
                configMapKeyRef:
                  name: nats-opts
                  key: curlbackoff
                  optional: true
            - name: CURL_REAUTH
              valueFrom:
                configMapKeyRef:
                  name: nats-opts
                  key: curlreauth
                  optional: true
            - name: VAULT_ADDR
              valueFrom:
                configMapKeyRef:
                  name: nats-opts
                  key: vaultaddr
            - name: VAULT_ROLE
              valueFrom:
                configMapKeyRef:
                  name: nats-opts
                  key: vaultrole
            - name: VAULT_KUBE_MOUNT
              valueFrom:
                configMapKeyRef:
                  name: nats-opts
                  key: vaultkubemount
            - name: KV_MOUNT
              valueFrom:
                configMapKeyRef:
                  name: nats-opts
                  key: kvmount
            - name: KV_PATH
              valueFrom:
                configMapKeyRef:
                  name: nats-opts
                  key: kvpath
          volumeMounts:
            - name: config-pass
              mountPath: /etc/natspass
            - name: config
              mountPath: /etc/nats
            - name: init-scripts
              mountPath: /home/nats
      containers:
        - name: nats
          image: nats:2-alpine
          command: ['nats-server']
          args: ['-c', '/etc/nats/server.conf']
          ports:
            - name: nats
              containerPort: 4222
            - name: cluster
              containerPort: 6222
          volumeMounts:
            - name: config-pass
              mountPath: /etc/nats
      volumes:
        - name: config
          configMap:
            name: nats-config
        - name: init-scripts
          configMap:
            name: nats-init-scripts
        - name: config-pass
          emptyDir: {}
  volumeClaimTemplates: []
